#!/bin/bash
# Auto-generate handoff.yaml on session stop
# spec/plan/ にタスクファイルがある場合のみ生成

set -euo pipefail

PLAN_DIR="spec/plan"
HANDOFF_FILE="${PLAN_DIR}/handoff.yaml"
TASKS_FILE="${PLAN_DIR}/tasks.md"

# spec/plan/ が存在しない場合はスキップ
if [[ ! -d "$PLAN_DIR" ]]; then
  exit 0
fi

# tasks.md が存在しない場合はスキップ
if [[ ! -f "$TASKS_FILE" ]]; then
  exit 0
fi

# タスク状態を解析
COMPLETED=$(grep -cE '^\s*-\s*\[x\]' "$TASKS_FILE" 2>/dev/null || true)
COMPLETED=${COMPLETED:-0}
COMPLETED=$((COMPLETED + 0))  # 数値化

TOTAL=$(grep -cE '^\s*-\s*\[[ x]\]' "$TASKS_FILE" 2>/dev/null || true)
TOTAL=${TOTAL:-0}
TOTAL=$((TOTAL + 0))  # 数値化

# 現在のフェーズを検出（未完了タスクがある最初のフェーズ）
CURRENT_PHASE=""
CURRENT_TASK=""
while IFS= read -r line; do
  if echo "$line" | grep -qE '^##\s+Phase'; then
    CURRENT_PHASE=$(echo "$line" | sed 's/^##[[:space:]]*//')
  fi
  if echo "$line" | grep -qE '^\s*-\s*\[ \]'; then
    if [[ -z "$CURRENT_TASK" ]]; then
      CURRENT_TASK=$(echo "$line" | sed 's/^[[:space:]]*-[[:space:]]*\[ \][[:space:]]*//')
    fi
  fi
done < "$TASKS_FILE"

# 完了フェーズをリスト
COMPLETED_PHASES=""
PHASE_NAME=""
PHASE_TOTAL=0
PHASE_DONE=0
while IFS= read -r line; do
  if echo "$line" | grep -qE '^##\s+Phase'; then
    if [[ -n "$PHASE_NAME" && "$PHASE_TOTAL" -gt 0 && "$PHASE_DONE" -eq "$PHASE_TOTAL" ]]; then
      COMPLETED_PHASES="${COMPLETED_PHASES}  - \"${PHASE_NAME}\"\n"
    fi
    PHASE_NAME=$(echo "$line" | sed 's/^##[[:space:]]*//')
    PHASE_TOTAL=0
    PHASE_DONE=0
  fi
  if echo "$line" | grep -qE '^\s*-\s*\[[ x]\]'; then
    PHASE_TOTAL=$((PHASE_TOTAL + 1))
    if echo "$line" | grep -qE '^\s*-\s*\[x\]'; then
      PHASE_DONE=$((PHASE_DONE + 1))
    fi
  fi
done < "$TASKS_FILE"
# 最後のフェーズ
if [[ -n "$PHASE_NAME" && "$PHASE_TOTAL" -gt 0 && "$PHASE_DONE" -eq "$PHASE_TOTAL" ]]; then
  COMPLETED_PHASES="${COMPLETED_PHASES}  - \"${PHASE_NAME}\"\n"
fi

# 進捗率計算
PROGRESS=0
if [[ "$TOTAL" -gt 0 ]]; then
  PROGRESS=$(( (COMPLETED * 100) / TOTAL )) || PROGRESS=0
fi

# handoff.yaml 生成
cat > "$HANDOFF_FILE" << EOF
# Auto-generated by o-m-cc on session stop
updated_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
status: "$([ "$PROGRESS" -eq 100 ] && echo "completed" || echo "in_progress")"

progress:
  completed: ${COMPLETED}
  total: ${TOTAL}
  percentage: "${PROGRESS}%"

current_task:
  phase: "${CURRENT_PHASE:-none}"
  task: "${CURRENT_TASK:-none}"

completed_phases:
$(echo -e "${COMPLETED_PHASES:-  []}")

plan_files:
  requirements: $([ -f "${PLAN_DIR}/requirements.md" ] && echo "true" || echo "false")
  design: $([ -f "${PLAN_DIR}/design.md" ] && echo "true" || echo "false")
  tasks: $([ -f "${PLAN_DIR}/tasks.md" ] && echo "true" || echo "false")
  orchestration: $([ -f "${PLAN_DIR}/orchestration.yml" ] && echo "true" || echo "false")

next_steps: []
EOF

exit 0
