#!/bin/bash
# Auto-generate handoff.yaml on session stop
# spec/plan/ にタスクファイルがある場合のみ生成

set -euo pipefail

PLAN_DIR="spec/plan"
HANDOFF_FILE="${PLAN_DIR}/handoff.yaml"
TASKS_FILE="${PLAN_DIR}/tasks.md"

# spec/plan/ が存在しない場合はスキップ
if [[ ! -d "$PLAN_DIR" ]]; then
  exit 0
fi

# tasks.md が存在しない場合はスキップ
if [[ ! -f "$TASKS_FILE" ]]; then
  exit 0
fi

# 現在のタスク状態を解析
# IN_PROGRESS のタスクを検出
CURRENT_TASK=""
if grep -qiE '^\s*-\s*\[.\]\s*.*IN.PROGRESS|status.*in.progress|🔄' "$TASKS_FILE" 2>/dev/null; then
  CURRENT_TASK=$(grep -iE '^\s*-\s*\[.\]\s*.*IN.PROGRESS|status.*in.progress|🔄|TASK-[0-9]+.*進行' "$TASKS_FILE" | head -1 | sed 's/^[[:space:]]*//')
fi

# 完了タスクをカウント
COMPLETED=$(grep -ciE '^\s*-\s*\[x\]|status.*completed|✅.*TASK' "$TASKS_FILE" 2>/dev/null || echo "0")
TOTAL=$(grep -ciE '^\s*-\s*\[.\]|TASK-[0-9]+' "$TASKS_FILE" 2>/dev/null || echo "0")

# 進捗率計算
if [[ "$TOTAL" -gt 0 ]]; then
  PROGRESS=$(( (COMPLETED * 100) / TOTAL ))
else
  PROGRESS=0
fi

# handoff.yaml 生成
cat > "$HANDOFF_FILE" << EOF
# Auto-generated by o-m-cc on session stop
updated_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
status: "$([ "$PROGRESS" -eq 100 ] && echo "completed" || echo "in_progress")"

progress:
  completed: ${COMPLETED}
  total: ${TOTAL}
  percentage: "${PROGRESS}%"

current_task: "${CURRENT_TASK:-none}"

plan_files:
  requirements: $([ -f "${PLAN_DIR}/requirements.md" ] && echo "true" || echo "false")
  design: $([ -f "${PLAN_DIR}/design.md" ] && echo "true" || echo "false")
  tasks: $([ -f "${PLAN_DIR}/tasks.md" ] && echo "true" || echo "false")
  orchestration: $([ -f "${PLAN_DIR}/orchestration.yml" ] && echo "true" || echo "false")

next_steps: []
EOF

exit 0
